language: node_js
node_js:
- '0.12'
sudo: false
cache:
  directories:
  - node_modules
before_install:
- export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
- npm config set spin false
- npm install -g npm@^2
install:
- npm install -g bower
- npm install
- bower install
script:
- npm test
- npm build
deploy:
  provider: s3
  access_key_id: yAKIAJOFT4HCPSXQWVO7Q
  secret_access_key:
    secure: aNmtONRxgqmy86a21JaT1lApE5Bf+jtLK0Htp2dw/2Lp/7AnKDL/tHntGVntsD08hBTeMDPUjWyuNrX7F/E4qhhEdbazbGLYWVGJKD4/I4ItLgae2P8rteDTe/A6ZPoQcw4LBbt9whVAulnTUoolsXHFWtt/P3SB9Yf5bslNWecKLKVkw4KpAmJ6fBZ5F3W7Dpj47n/CKTXV6lSk2tF+StZqCotveV8ry5Na2lMn/mEAhFSJyNYB8mBoIRqMFVJJPogZiDf54HVF876gt2+11y8HZaSKPPV0+qf5NCtFiGGZROugLgSPtD9pT8Lj7aVpu95NDgAP1sJjvSXvnQXdO+p7Yb0CdDCe23RZLcKJWhxJV9XaHzWcIp8aAd9CqfNRhlWhcOhGeUESHlzzAUVCs4AbMnroQEQ5Y4pWx1sgomOT2giqeSto8veHkaOxvkMjg09mSC6mJchymKl5tMz81LPasZPUpFrBS6lFmqj2+39qBQj7qvfcQbJ9yJbUoqhqI8gX+cue3hvTpgCpRffKsEg64vhewWUXYlBHOE6OEIEtw5AObk2PLJTXfRiUs58fUOzuAcdxzrHag+K7eEXWSR7fFp5ZupOot0m1A7gPbqSfDyQDxO7XECzUegyviJlTo9MBNBe+s/eMH+SJpL/ykhhVV800LoAA1rkBTmbfNBQ=
  bucket: tickets.niceday-group.com
  local-dir: dist
  acl: public_read
  on:
    repo: NiceDay-Group/tickets-by-ember
