language: node_js
node_js:
- '0.12'
sudo: false
cache:
  directories:
  - node_modules
before_install:
- export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
- npm config set spin false
- npm install -g npm@^2
install:
- npm install -g bower
- npm install
- bower install
script:
- npm run build
deploy:
  provider: s3
  access_key_id: AKIAIJTJ7NMVXBI3WASQ
  secret_access_key:
    secure: H5kHb/nT+UDh6jYUM0/zGKx0dhDPKLplczVp2I6qeZq+Mm3RFxJ5C2rAgHCLAr3zgeMrWuRZ6x+DVtit9g2WDzTtc+rVbeRaGVT1mkSt5gLnszwVDJBrllt8VnOZ6SQ9+l9x4e7WJfE0mNwOoAxD3saC2lNBWXHqhjlF2pNOJhcSIVjxRNMsNt4BD6RfgPdamxTSU33BCu2poD/vRrRtBMTkoHx12o7Xm+18ob/ewYeD6PMg9NzaI26k/0IEPAXSllvXAoK2IVNvhv9yqwbdA8Ap4vGzrNlsdSlj2ubFR6gPoCDPi1HXVCP+zwf4RO17RxJeqFoJkp3ItXncKBEXfNmL08789z3/f/AL8WTUSVPvNUnKJxvTYK5QQ1JiVLuw4AhjedZnp5k/rKtrhVlbKg73hxsPrm8z6KetT6tAsczUlMFxll/pVnEnnL6SDNmk2iDyxnLOo1RmzDuhgnugoxBgsKjaYrvlCZ4/iAYtVRx3zkQL4YA6aLaowrG4y5or7jxV7+8dfELHQsK+uLJF5ya/0D8ZXzWb5RS0FKfdqRPa2vxQfXVafz406mqAf7l2uRTOE2Yx0PLr7q5ZhYdHDPeUAmui+QSzHWKiMNcbrXJv3+xKrahtCVUhMrWXAYWunI+6Gcm/YaXthEK69p1S3IQj9I3Esv5Jg1Ba/nNvAns=
  bucket: tickets.mrdeer.net
  skip_cleanup: true
  local-dir: dist
  acl: public_read
  region: eu-central-1
  on:
    repo: mr-deer/tickets-ember
